In [1]:
import name_conversions as c
import pandas as pd

In [3]:
c.alpha_to_common('NOCA')

'Northern Cardinal'

In [2]:
bbl_alpha = pd.read_csv('./resources/bbl-alpha-codes_2021.csv')
ibp_alpha = pd.read_csv('./resources/ibp-alpha-codes_2021.csv')
species_table = pd.read_csv('./resources/species_table.csv')

In [4]:
bbl_alpha.head()

,true_alpha,common_name,scientific_name,t_and_e,comments
0,WEGR,Western Grebe,Aechmophorus occidentalis,NaN,NaN
1,CLGR,Clark's Grebe,Aechmophorus clarkii,NaN,NaN
2,WCGR,Western/Clark's Grebe,NaN,NaN,Unspecified Aechmophorus occidentalis or A. cl...
3,RNGR,Red-necked Grebe,Podiceps grisegena,NaN,NaN
4,HOGR,Horned Grebe,Podiceps auritus,Y,Magdalen Islands population is endangered. | L...

In [7]:
ibp_alpha.head()

,non_species,true_alpha,conflict,common_name,scientific_name,true_alpha_6,conflict_6
0,NaN,HITI,NaN,Highland Tinamou,Nothocercus bonapartei,NOTBON,NaN
1,NaN,GRTI,NaN,Great Tinamou,Tinamus major,TINMAJ,NaN
2,NaN,LITI,NaN,Little Tinamou,Crypturellus soui,CRYSOU,NaN
3,NaN,THTI,NaN,Thicket Tinamou,Crypturellus cinnamomeus,CRYCIN,NaN
4,NaN,SBTI,NaN,Slaty-breasted Tinamou,Crypturellus boucardi,CRYBOU,NaN

In [13]:
species_table['scientific_name'] = species_table['scientific'].apply(lambda x: (x[0].upper() + x[1:].lower()).replace('-', ' '))

In [14]:
species_table.head()

,scientific,xc_common,bn_code,bn_common,bn_mapping_in_xc_dataset,relationship,scientific_name
0,dendrocygna-autumnalis,blackbelliedwhistlingduck,bbwduc,blackbelliedwhistlingduck,dendrocygna-autumnalis,NaN,Dendrocygna autumnalis
1,anser-caerulescens,snowgoose,snogoo,snowgoose,anser-caerulescens,NaN,Anser caerulescens
2,anser-albifrons,greaterwhitefrontedgoose,gwfgoo,greaterwhitefrontedgoose,anser-albifrons,NaN,Anser albifrons
3,branta-bernicla,brantgoose,brant,brant,branta-bernicla,"Same species, different common name",Branta bernicla
4,branta-hutchinsii,cacklinggoose,cacgoo1,cacklinggoose,branta-hutchinsii,NaN,Branta hutchinsii

In [15]:
len(set(species_table['scientific_name'])-set(ibp_alpha['scientific_name']))

28

In [18]:
len(set(ibp_alpha['scientific_name'])-set(species_table['scientific_name']))

1799

In [21]:
len(set(species_table['scientific_name'])-set(bbl_alpha['scientific_name']))

47